[package]
name = "faultline-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
faultline-common = { workspace = true }
faultline-catalog = { workspace = true }
faultline-state = { workspace = true }
faultline-engine = { workspace = true }
faultline-replay = { workspace = true }
faultline-inference = { workspace = true }

